export const FONTS = {
  SourceSansProBold: require("../assets/fonts/SourceSansPro-Bold.ttf"),
  SourceSansProRegular: require("../assets/fonts/SourceSansPro-Regular.ttf"),
  SourceSansProSemiBold: require("../assets/fonts/SourceSansPro-SemiBold.ttf"),
  LatoBlack: require("../assets/fonts/Lato-Black.ttf"),
  LatoBlackItalic: require("../assets/fonts/Lato-BlackItalic.ttf"),
  LatoBold: require("../assets/fonts/Lato-Bold.ttf"),
  LatoBoldItalic: require("../assets/fonts/Lato-BoldItalic.ttf"),
  LatoRegular: require("../assets/fonts/Lato-Regular.ttf"),
  LatoItalic: require("../assets/fonts/Lato-Italic.ttf"),
  LatoLight: require("../assets/fonts/Lato-Light.ttf"),
  LatoLightItalic: require("../assets/fonts/Lato-LightItalic.ttf"),
  LatoThin: require("../assets/fonts/Lato-Thin.ttf"),
  LatoThinItalic: require("../assets/fonts/Lato-ThinItalic.ttf"),
  Billabong: require("../assets/fonts/Billabong.ttf"),
};
