import Logo from "../assets/icons/logo.svg";
import RightArrow from "../assets/icons/right-arrow.svg";
import Close from "../assets/icons/close.svg";
import Heart from "../assets/icons/heart.svg";
import Camera from "../assets/icons/camera.svg";
import RedRightArrow from "../assets/icons/red-right-arrow.svg";
import WhiteCheck from "../assets/icons/white-check.svg";
import WhitePhotography from "../assets/icons/white-photography.svg";
import WhiteShopping from "../assets/icons/white-shopping.svg";
import WhiteKaraoke from "../assets/icons/white-karaoke.svg";
import WhiteYoga from "../assets/icons/white-yoga.svg";
import WhiteCooking from "../assets/icons/white-cooking.svg";
import WhiteTennis from "../assets/icons/white-tennis.svg";
import WhiteRun from "../assets/icons/white-run.svg";
import WhiteSwimming from "../assets/icons/white-swimming.svg";
import WhiteArt from "../assets/icons/white-art.svg";
import WhiteTraveling from "../assets/icons/white-traveling.svg";
import WhiteExtreme from "../assets/icons/white-extreme.svg";
import WhiteMusic from "../assets/icons/white-music.svg";
import WhiteDrink from "../assets/icons/white-drink.svg";
import WhiteVideoGame from "../assets/icons/white-video-game.svg";
import RedPhotography from "../assets/icons/red-photography.svg";
import RedShopping from "../assets/icons/red-shopping.svg";
import RedKaraoke from "../assets/icons/red-karaoke.svg";
import RedYoga from "../assets/icons/red-yoga.svg";
import RedCooking from "../assets/icons/red-cooking.svg";
import RedTennis from "../assets/icons/red-tennis.svg";
import RedRun from "../assets/icons/red-run.svg";
import RedSwimming from "../assets/icons/red-swimming.svg";
import RedArt from "../assets/icons/red-art.svg";
import RedTraveling from "../assets/icons/red-traveling.svg";
import RedExtreme from "../assets/icons/red-extreme.svg";
import RedMusic from "../assets/icons/red-music.svg";
import RedDrink from "../assets/icons/red-drink.svg";
import RedGame from "../assets/icons/red-game.svg";
import WhiteGB from "../assets/icons/white-bg.svg";
import DeafaultAvatar from "../assets/images/default-avatar.svg";
import Message from "../assets/icons/message.svg";
import Flash2 from "../assets/icons/flash.svg";
import InforCircle from "../assets/icons/info-circle.svg";
import Like from "../assets/icons/like.svg";
import Menu from "../assets/icons/menu.svg";
import Pencil from "../assets/icons/pencil.svg";
import Key from "../assets/icons/key.svg";
import User from "../assets/icons/user.svg";
import LeftArrow from "../assets/icons/left-arrow.svg";
import RedLeftArrow from "../assets/icons/red-left-arrow.svg";

export const LogoIcon = Logo.toString();
export const RightArrowIcon = RightArrow.toString();
export const CloseIcon = Close.toString();
export const HeartIcon = Heart.toString();
export const CameraIcon = Camera.toString();
export const RedRightArrowIcon = RedRightArrow.toString();
export const WhiteCheckIcon = WhiteCheck.toString();
export const WhitePhotographyIcon = WhitePhotography.toString();
export const WhiteShoppingIcon = WhiteShopping.toString();
export const WhiteKaraokeIcon = WhiteKaraoke.toString();
export const WhiteYogaIcon = WhiteYoga.toString();
export const WhiteCookingIcon = WhiteCooking.toString();
export const WhiteTennisIcon = WhiteTennis.toString();
export const WhiteRunIcon = WhiteRun.toString();
export const WhiteSwimmingIcon = WhiteSwimming.toString();
export const WhiteArtIcon = WhiteArt.toString();
export const WhiteTravelingIcon = WhiteTraveling.toString();
export const WhiteExtremeIcon = WhiteExtreme.toString();
export const WhiteMusicIcon = WhiteMusic.toString();
export const WhiteDrinkIcon = WhiteDrink.toString();
export const WhiteVideoGameIcon = WhiteVideoGame.toString();
export const RedPhotographyIcon = RedPhotography.toString();
export const RedShoppingIcon = RedShopping.toString();
export const RedKaraokeIcon = RedKaraoke.toString();
export const RedYogaIcon = RedYoga.toString();
export const RedCookingIcon = RedCooking.toString();
export const RedTennisIcon = RedTennis.toString();
export const RedRunIcon = RedRun.toString();
export const RedSwimmingIcon = RedSwimming.toString();
export const RedArtIcon = RedArt.toString();
export const RedTravelingIcon = RedTraveling.toString();
export const RedExtremeIcon = RedExtreme.toString();
export const RedMusicIcon = RedMusic.toString();
export const RedDrinkIcon = RedDrink.toString();
export const RedGameIcon = RedGame.toString();
export const WhiteGBIcon = WhiteGB.toString();
export const DeafaultAvatarIcon = DeafaultAvatar.toString();
export const MessageIcon = Message.toString();
export const Flash2Icon = Flash2.toString();
export const InforCircleIcon = InforCircle.toString();
export const LikeIcon = Like.toString();
export const MenuIcon = Menu.toString();
export const PencilIcon = Pencil.toString();
export const KeyIcon = Key.toString();
export const UserIcon = User.toString();
export const LeftArrowIcon = LeftArrow.toString();
export const RedLeftArrowIcon = RedLeftArrow.toString();
